name: Update WakaTime Stats

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.Named }}  # Ensure this secret matches your WakaTime API key
          INCLUDE_PROFILE_VIEWS: true  # Optional: Include profile views
          INCLUDE_CODE_TIME: true  # Optional: Include code time
          INCLUDE_LANGUAGES: true  # Optional: Include programming languages
          INCLUDE_PROJECTS: true  # Optional: Include projects
          INCLUDE_COMMITS: true  # Optional: Include commit activity stats
